# Meta Data for SEO

## Homepage
title = "M-API"
titleSeparator = "-"
titleAddition = "FakeCo API Documentation"
description = "Welcome to the FakeCo API Documentation and Developer resource portal."

## Open Graph + Twitter Cards
images = ["mapi.png"]
twitterSite = "marketplacer_"
twitterCreator = "marketplacer_"
facebookAuthor = "marketplacer1"
facebookPublisher = "marketplacer1"
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "logo-mapi.png"
schemaTwitter = "https://twitter.com/marketplacer_"
schemaLinkedIn = "https://www.linkedin.com/company/marketplacer/"
schemaGitHub = "https://github.com/marketplacer"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Made by FakeCo."

# Alert
alert = true
alertText = "THIS IS A DEVELOPMENT SITE - INFORMATION CONTAINED WITHIN IS FOR TESTING PURPOSES ONLY"

# Edit Page
docsRepo = "https://github.com/h-enk/doks"
editPage = false

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = true
  bootStrapJs = false
  breadCrumb = true
  highLight = true
  kaTex = false
